spring:

  config:
    import:
      - classpath:base.yaml
      - classpath:controller-paths.yaml
      - classpath:error-messages.yaml
      - classpath:cors.yaml
      - classpath:email-service.yaml
      - classpath:token.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/restful-api-jwt
    username: cris6h16
    password: 12345678
    hikari:
      schema: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    root: debug


