frontend:
  core: ${FRONTEND_URL}

swagger:
  ui:
    core: ${SWAGGER_CORE}

db:
  host: ${PSQL_HOSTNAME}
  port: ${PSQL_PORT}
  db-name: ${PSQL_DB_NAME}
  username: ${PSQL_USER}
  password: ${PSQL_PASS}
  hikari:
    schema: prod

jpa:
  show-sql: false
  properties:
    hibernate:
      format_sql: false
      ddl-auto: update

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  password: ${REDIS_PASS}

token:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

mail:
  username: ${MAIL_USER}
  password: ${MAIL_PASS}

logging:
  level:
    root: error
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/restful-api-jwt.%d{yyyy-MM-dd}.log  # one per day
      clean-history-on-start: false
      max-history: 7  # 7 days
      total-size-cap: 200MB  # limit total logs size



spring:

  config:
    import:
      - classpath:base.yaml
      - classpath:mail.yaml