frontend:
  core: ${FRONTEND_CORE}

swagger:
  ui:
    core: ${SWAGGER_CORE}

db:
  host: ${PSQL_HOSTNAME}
  port: ${PSQL_PORT}
  db-name: ${PSQL_DB_NAME}
  username: ${PSQL_USER}
  password: ${PSQL_PASS}
  hikari:
    schema: prod

jpa:
  show-sql: false
  properties:
    hibernate:
      format_sql: false
      ddl-auto: update

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  password: ${REDIS_PASS}




logging:
  level:
    root: error
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/restful-api-jwt.%d{yyyy-MM-dd}.log  # one per day
      clean-history-on-start: false
      max-history: 7  # 7 days
      total-size-cap: 200MB  # limit total logs size


spring:

  config:
    import:
      - classpath:base.yaml

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: smtp.gmail.com
            checkserveridentity: true
        debug: false



  # My ISP is blocking port 587, so I have to use port 465
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ${MAIL_USER}
  #    password: ${MAIL_PASS}
  #    protocol: smtp
  #    properties:
  #      mail:
  #        debug: true
  #        transport:
  #          protocol: smtp
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true


  # SSL disabled due to chrome is blocking self-signed certificates...

#server:
#  ssl:
#    key-store: classpath:${JKS_NAME}
#    key-store-password: ${KEY_STORE_PASS}
#    key-store-type: JKS
#    key-alias: ${KEY_ALIAS}
#    enabled: true