frontend:
  core: http://mocked.com

swagger:
  ui:
    core: http://mocked2.com

db:
  host: ${PSQL_HOSTNAME}
  port: ${PSQL_PORT}
  db-name: ${PSQL_DB_NAME}
  username: ${PSQL_USER}
  password: ${PSQL_PASS}
  hikari:
    schema: prod

jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  password: ${REDIS_PASS}



logging:
  level:
    root: trace


spring:
  config:
    import:
      - classpath:base.yaml



