frontend:
  core: http://mocked.com

swagger:
  ui:
    core: http://localhost:8015

db:
  host: ${PSQL_HOSTNAME}
  port: ${PSQL_PORT}
  db-name: ${PSQ L_DB_NAME}
  username: ${PSQL_USER}
  password: ${PSQL_PASS}
  hikari:
    schema: dev

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: create

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  password: ${REDIS_PASS}


logging:
  level:
    root: debug


spring:
  config:
    import:
      - classpath:base.yaml

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: smtp.gmail.com
            checkserveridentity: true
        debug: false

