frontend:
  core: http://mocked.com

swagger:
  ui:
    core: http://localhost:8015

db:
  host: localhost
  port: 9000
  db-name: api
  username: cris6h16
  password: 12345678
  hikari:
    schema: dev

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: create

redis:
  host: localhost
  port: 6000
  password: admin



mail:
  username: ${MAIL_USER}
  password: ${MAIL_PASS}

logging:
  level:
    root: debug


spring:
  config:
    import:
      - classpath:base.yaml
      - classpath:mail.yaml

