frontend:
  core: http://mocked.com

swagger:
  ui:
    core: http://mocked2.com

db:
  host: localhost
  port: 9000
  db-name: api
  username: cris6h16
  password: 12345678
  hikari:
    schema: prod

jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create

redis:
  host: localhost
  port: 6000
  password: admin



logging:
  level:
    root: trace


spring:
  config:
    import:
      - classpath:base.yaml



