spring:

  application:
    name: restful-api-jwt

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  error:
    include-message: never
    include-exception: off
    include-stacktrace: never




