cors:
  path-pattern: /**
  allowed-origins:
    - ${frontend.core}
    - ${swagger.ui.core}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers: # when is empty will be '*'
    - Content-Type
    - accept
  exposed-headers: # when is empty will be '*'
    - Set-Cookie
  allow-credentials: true
  max-age: 3600 #seconds