cors:
  path-pattern: /**
  allowed-origins:
    - ${frontend.core}
    - ${swagger.ui.core}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
  allowed-headers:
    - Content-Type
    - Authorization
  exposed-headers:
    - Content-Type
  allow-credentials: false
  max-age: 3600 #seconds