spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${mail.username}
    password: ${mail.password}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: smtp.gmail.com
            checkserveridentity: true
        debug: false


  # My ISP is blocking port 587, so I have to use port 465
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ${MAIL_USER}
  #    password: ${MAIL_PASS}
  #    protocol: smtp
  #    properties:
  #      mail:
  #        debug: true
  #        transport:
  #          protocol: smtp
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true

