jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    refresh:
      expiration:
        secs: 1296000 # 15 days
      cookie:
        name: refreshToken
        path: ${controller.authentication.refresh-access-token}
    access:
      expiration:
        secs: 1800 # 30 minutes
      cookie:
        name: accessToken
        path: ${controller.base} # todo: add test if access i expired the refresh token must be processed in the jwt filter

      request:
        email:
          verification:
            secs: 86400 # 1 day todo: add to docs this change ( initiallly was 5 minutes)
          delete-account:
            secs: 1800 # 30 minutes
          update-email:
            secs: 1800 # 30 minutes
          reset:
            password:
              secs: 1800 # 30 minutes
